language: go

go:
  - 1.10.x

env:
  global:
  - REPO: $TRAVIS_REPO_SLUG
  - VERSION: $TRAVIS_TAG

before_script:
  - make test
  - make cover
  - go get -u github.com/haya14busa/goverage
  - godacov -t $CODACY_TOKEN -r ./coverage.out -c $TRAVIS_COMMIT

script:
- make docker
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io
- make upload
