[[constraint]]
  branch = "master"
  name = "github.com/bborbe/assert"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/bborbe/teamvault_utils"
